deployment_flake = "github:kuutamolabs/deployment-example"
name = "kld-00"
nixos_module = "kld-node"
extra_nixos_modules = []
ipv4_address = "51.89.232.7"
ipv4_cidr = 24
ipv4_gateway = "51.89.232.254"
ipv6_address = "2001:41d0:800:2507::1"
ipv6_cidr = 64
ipv6_gateway = "2001:41d0:800:25ff:ff:ff:ff:ff"
install_ssh_user = "root"
ssh_hostname = "51.89.232.7"
public_ssh_keys = ["""
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQuRs44Ry//RaVddE3ZxR7wKMM7h8BAmUpud3urpGQ3LbxrhbCGKQoRV1OJEEdnYSoAk4bMvtEfkkXFZAioSJxZ0Flult983LHWCCB0pYkq/Hw0UqgLZV2TjyYIqLxAlhDh7vbivmlP0nDPQ3dV33GrIcPK9zShyI58JWJTna/Lf0XsLN2Iy72xo15R8FnwVL+NtCIVBSeP5huYVy8Z65Zv+Tcg8vXQCL2raNqwNE/B1NQary5vgfId76Q6w5gyvDXWZITskNOmmbmB5aZ/1mxWh1m16BsxO61upchopjIN/Wh6meipt3EY5FEibJp2GLUEQLEoDcZ6hvtZKmS7vhiroHAWb+u2MM/rJnNmIfVVRp2MlDd6wWfb9ZwpGb1YypS5qYAIocsjlMfGnonRW9ZgA/sWbWhp4aLKdncpyxw8qCPnEEf2E+mKmVCCRabhjs1yoZ/e99r2sJUruWF4udHjMOIVietMS166npRPIdOkz/23M/yL8Z7b7BfP0IkUq8= yanganto@yanganto-laptop
""", "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID4LjD2ootj280nAfOtT56CVvMtQjQeJnlSGzvJjrGIT", "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILEf0w/dK0xroJn/knxSdRPWfou2NqaW+n1sEicSol5P", "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIb3uuMqE/xSJ7WL/XpJ6QOj4aSmh0Ga+GtmJl3CDvljGuIeGCKh7YAoqZAi051k5j6ZWowDrcWYHIOU+h0eZCesgCf+CvunlXeUz6XShVMjyZo87f2JPs2Hpb+u/ieLx4wGQvo/Zw89pOly/vqpaX9ZwyIR+U81IAVrHIhqmrTitp+2FwggtaY4FtD6WIyf1hPtrrDecX8iDhnHHuGhATr8etMLwdwQ2kIBx5BBgCoiuW7wXnLUBBVYeO3II957XP/yU82c+DjSVJtejODmRAM/3rk+B7pdF5ShRVVFyB6JJR+Qd1g8iSH+2QXLUy3NM2LN5u5p2oTjUOzoEPWZo7lykZzmIWd/5hjTW9YiHC+A8xsCxQqs87D9HK9hLA6udZ6CGkq4hG/6wFwNjSMnv30IcHZzx6IBihNGbrisrJhLxEiKWpMKYgeemhIirefXA6UxVfiwHg3gJ8BlEBsj0tl/HVARifR2y336YINEn8AsHGhwrPTBFOnBTmfA/VnP1NlWHzXCfVimP6YVvdoGCCnAwvFuJ+ZuxmZ3UzBb2TenZZOzwzV0sUzZk0D1CaSBFJUU3oZNOkDIM6z5lIZgzsyKwb38S8Vs3HYE+Dqpkfsl4yeU5ldc6DwrlVwuSIa4vVus4eWD3gDGFrx98yaqOx17pc4CC9KXk/2TjtJY5xmQ== lass@yubikey"]
disks = ["/dev/nvme0n1", "/dev/nvme1n1"]
bitcoind_disks = []
telegraf_has_monitoring = false
telegraf_config_hash = "13646096770106105413"
api_ip_access_list = []
kld_preset_mnemonic = false

[[cockroach_peers]]
name = "kld-00"
ipv4_address = "51.89.232.7"
ipv6_address = "2001:41d0:800:2507::1"
